/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketsystem;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author Gouhar Ali
 */
public class ADMIN_MAIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN_MAIN
     */
    public ADMIN_MAIN() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    
           
    public String currentdate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year =cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        if(month==12){
            month=1;
        }else{
            month++;
        }
        return String.valueOf(day+"_"+month+"_"+year);
    }
    

    
    
    
    public static void exportDatabase(String host, String port, String dbName, String user, String password, String outputFile, String mysqldumpPath) {
        try {
            // Build the mysqldump command
            String command = mysqldumpPath + " -h " + host + " -P " + port + " -u " + user +
                    (password.isEmpty() ? "" : " -p" + password) + " " + dbName + " -r " + outputFile;

            // Create a ProcessBuilder to run the command
            ProcessBuilder pb = new ProcessBuilder("cmd.exe", "/c", command);
            pb.redirectErrorStream(true);  // Merge error stream into output stream

            // Start the process
            Process process = pb.start();

            // Read the process output
            BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);  // Print command output (optional)
            }

            // Wait for the process to complete
            int exitCode = process.waitFor();
            if (exitCode == 0) {
                System.out.println("Database exported successfully to " + outputFile);
            } else {
                System.out.println("Error occurred during export. Exit code: " + exitCode);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane11 = new panal.pane1();
        button3 = new ALL_UI_1.Button();
        button4 = new ALL_UI_1.Button();
        jLabel1 = new javax.swing.JLabel();
        button6 = new ALL_UI_1.Button();
        button7 = new ALL_UI_1.Button();
        button2 = new ALL_UI_1.Button();
        button5 = new ALL_UI_1.Button();
        pane21 = new panal.pane2();
        button1 = new ALL_UI_1.Button();
        jLabel2 = new javax.swing.JLabel();
        pane31 = new panal.pane3();
        pane32 = new panal.pane3();
        pane34 = new panal.pane3();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-category-48.png"))); // NOI18N
        button3.setText("ADD CATEGORI");
        button3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button3.setRippleColor(new java.awt.Color(0, 153, 153));
        button3.setShadowColor(new java.awt.Color(0, 0, 0));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        pane11.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 93));

        button4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-pos-100.png"))); // NOI18N
        button4.setText("SALE ( POS )");
        button4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button4.setRippleColor(new java.awt.Color(0, 153, 153));
        button4.setShadowColor(new java.awt.Color(0, 0, 0));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        pane11.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 110));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOME");
        pane11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 214, 70));

        button6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-database-syncing-complete-local-drive-and-connected-with-other-pc-48.png"))); // NOI18N
        button6.setText("BACKUP");
        button6.setRound(20);
        button6.setShadowColor(new java.awt.Color(255, 255, 51));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        pane11.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 210, 61));

        button7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-logout-30.png"))); // NOI18N
        button7.setText("LOGOUT");
        button7.setRound(20);
        button7.setShadowColor(new java.awt.Color(255, 255, 51));
        pane11.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 210, 61));

        button2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-seller-50.png"))); // NOI18N
        button2.setText("ADD SALESMAN");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.setRippleColor(new java.awt.Color(0, 153, 153));
        button2.setShadowColor(new java.awt.Color(0, 0, 0));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        pane11.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 210, 90));

        button5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-products-50.png"))); // NOI18N
        button5.setText("PRODUCTS");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button5.setRippleColor(new java.awt.Color(0, 153, 153));
        button5.setShadowColor(new java.awt.Color(0, 0, 0));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        pane11.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 210, 90));

        bgpanal1.add(pane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, -1, 840));

        button1.setText("X");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.setShadowColor(new java.awt.Color(0, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pane21.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("POS SOFTWARE");
        pane21.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 40));
        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, 290, 170));
        bgpanal1.add(pane32, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 58, 283, 175));
        bgpanal1.add(pane34, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 290, 170));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        dispose();
        new AddProduct().setVisible(true);
    }//GEN-LAST:event_button5ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new Category().setVisible(true);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        dispose();
        new SalePOS().setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        dispose();
        new AddSeller().setVisible(true);
    }//GEN-LAST:event_button2ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
      
        
        
       String dbHost = "localhost";
        String dbPort = "3306";
        String dbName = "shop_db";  // Replace with your database name
        String dbUser = "root";               // XAMPP default user is 'root'
        String dbPassword = "";               // XAMPP default password for root is empty
        String outputFile = "E:\\db_backup\\backup_"+currentdate()+".sql";  // Path where you want to store the SQL file

        // Specify the path to the mysqldump executable in XAMPP
        String mysqldumpPath = "C:/xampp/mysql/bin/mysqldump.exe";

        exportDatabase(dbHost, dbPort, dbName, dbUser, dbPassword, outputFile, mysqldumpPath);
        
            
    }//GEN-LAST:event_button6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN_MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN_MAIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panal.bgpanal bgpanal1;
    private ALL_UI_1.Button button1;
    private ALL_UI_1.Button button2;
    private ALL_UI_1.Button button3;
    private ALL_UI_1.Button button4;
    private ALL_UI_1.Button button5;
    private ALL_UI_1.Button button6;
    private ALL_UI_1.Button button7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private panal.pane1 pane11;
    private panal.pane2 pane21;
    private panal.pane3 pane31;
    private panal.pane3 pane32;
    private panal.pane3 pane34;
    // End of variables declaration//GEN-END:variables
}
