/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketsystem;

import codeFiles.*;
import com.lowagie.text.pdf.PdfPRow;
import java.awt.*;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gouhar Ali
 */
public class Category extends javax.swing.JFrame {

    /**
     * Creates new form ITEMS
     */
    public Category() {
        initComponents();
        setBackground(new Color(0,0,0,0));
        ImageIcon img = new ImageIcon("src/ASSETS_files/pngwing.com.png");
        this.setIconImage(img.getImage());
        con= new ConnectDB(). AccessDBConnection();
        get_SetData();
        date.setText(currentdate());
        
    }

     public String currentdate(){
        
            
                
                Calendar cal=new GregorianCalendar();
                int month=cal.get(Calendar.MONTH);
                int year =cal.get(Calendar.YEAR);
                int day=cal.get(Calendar.DAY_OF_MONTH);
                String date ;
                if(month==12){
                    month=1;
                    date=day+" / "+(month)+" / "+year;
                    return date;
                }else{
                    month +=1;
                    date=day+" / "+(month)+" / "+year;
                    return date;
                }
                                
          
    }
    
    
    int xMouse;
    int yMouse;
    Connection con;
    PreparedStatement str;
    ResultSet rs;
    
    
    
    
    
    public void get_SetData(){
      try{
          
          str = con.prepareStatement("Select* from category");
          rs=str.executeQuery();
          DefaultTableModel df = (DefaultTableModel)jTable1.getModel();
          df.setRowCount(0);
          while(rs.next()){
            String [] row = {rs.getString("ID"),rs.getString("name"),rs.getString("description"),rs.getString("Date")};
            df.addRow(row);
          }
          
      }catch(Exception ex){
          JOptionPane.showMessageDialog(this, ex.getMessage());
      }
    }
    
    
    
    
    public boolean submit(){
        try{
            str = con.prepareStatement("INSERT INTO `category`(`name`,description,Date) VALUES (?,?,?)");
            str.setString(1, ITEMtxt.getText());
            str.setString(2, DEStxt.getText());
            str.setString(3, date.getText());
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    
    public boolean update(){
        try{
            String ID=IDtxt.getText();
            str = con.prepareStatement("UPDATE `category` SET `name`=?,`description`=? WHERE ID="+ID);
            str.setString(1, ITEMtxt.getText());
            str.setString(2, DEStxt.getText());
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    public boolean delete(){
       try{
            String ID=IDtxt.getText();
            str = con.prepareStatement("DELETE FROM `category` WHERE ID="+ID);
            str.executeUpdate();
            return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage(),"ERROR",2);
            return false;
        }
    }
    
    
    
    public boolean checkSideCase(){
        return ITEMtxt.getText().equals("") || DEStxt.getText().equals("");
    }
    
    
    public void tblClick(){
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        int srow = jTable1.getSelectedRow();
        IDtxt.setText(df.getValueAt(srow, 0).toString());
        ITEMtxt.setText(df.getValueAt(srow, 1).toString());
        DEStxt.setText(df.getValueAt(srow, 2).toString());
        saveBtn.setText("UPDATE");    
    }
    
    
    
    public void Newbtn(){
        get_SetData();
        IDtxt.setText("");
        ITEMtxt.setText("");
        DEStxt.setText("");
        saveBtn.setText("SAVE");
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane31 = new panal.pane3();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IDtxt = new javax.swing.JTextField();
        ITEMtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DEStxt = new javax.swing.JTextArea();
        saveBtn = new ALL_UI_1.Button();
        savebtn1 = new ALL_UI_1.Button();
        button2 = new ALL_UI_1.Button();
        button1 = new ALL_UI_1.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pane21 = new panal.pane2();
        jLabel29 = new javax.swing.JLabel();
        button3 = new ALL_UI_1.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(221, 217, 217));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADD CATEGORI");
        pane31.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, 60));

        date.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("DATE");
        pane31.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 410, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("ID");
        pane31.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 50, 50));

        IDtxt.setEditable(false);
        IDtxt.setBackground(new java.awt.Color(255, 204, 204));
        IDtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDtxt.setBorder(null);
        pane31.add(IDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 250, 50));

        ITEMtxt.setBackground(new java.awt.Color(204, 255, 255));
        ITEMtxt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ITEMtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ITEMtxt.setBorder(null);
        ITEMtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITEMtxtActionPerformed(evt);
            }
        });
        ITEMtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ITEMtxtKeyTyped(evt);
            }
        });
        pane31.add(ITEMtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 250, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("CATEGORI");
        pane31.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 110, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Description");
        pane31.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 360, 40));

        DEStxt.setColumns(20);
        DEStxt.setRows(5);
        jScrollPane2.setViewportView(DEStxt);

        pane31.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 360, 140));

        saveBtn.setText("SAVE");
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        saveBtn.setRippleColor(new java.awt.Color(51, 255, 51));
        saveBtn.setRound(20);
        saveBtn.setShadowColor(new java.awt.Color(0, 0, 0));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        pane31.add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 420, 70));

        savebtn1.setText("NEW");
        savebtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        savebtn1.setRippleColor(new java.awt.Color(51, 255, 51));
        savebtn1.setRound(20);
        savebtn1.setShadowColor(new java.awt.Color(0, 0, 0));
        savebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtn1ActionPerformed(evt);
            }
        });
        pane31.add(savebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 200, 70));

        button2.setBackground(new java.awt.Color(255, 204, 204));
        button2.setText("DELETE");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button2.setRippleColor(new java.awt.Color(255, 51, 51));
        button2.setRound(20);
        button2.setShadowColor(new java.awt.Color(0, 0, 0));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        pane31.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 200, 70));

        button1.setText("BACK");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setShadowColor(new java.awt.Color(0, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pane31.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 150, 60));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ITEM", "DESCRIPTION", "DATE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pane31.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 350, 440));

        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 810, 640));

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("ITEMS");
        jLabel29.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel29MouseDragged(evt);
            }
        });
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });
        pane21.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        button3.setBackground(new java.awt.Color(255, 204, 204));
        button3.setForeground(new java.awt.Color(0, 0, 153));
        button3.setText("X");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        pane21.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 0, 40, -1));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 40));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel29MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseDragged
        // TODO add your handling code here:

        int x =evt.getXOnScreen();
        int y =evt.getYOnScreen();
        this.setLocation(x-xMouse , y-yMouse);
    }//GEN-LAST:event_jLabel29MouseDragged

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
        // TODO add your handling code here:

        xMouse = evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_jLabel29MousePressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        tblClick();
    }//GEN-LAST:event_jTable1MouseClicked

    private void ITEMtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITEMtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITEMtxtActionPerformed

    private void ITEMtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ITEMtxtKeyTyped
        // TODO add your handling code here:
        
        String v = ITEMtxt.getText();
        if(v.length()>10){
            JOptionPane.showMessageDialog(this, "TOO LONG ENTRY");
            ITEMtxt.setText("");
        }
    }//GEN-LAST:event_ITEMtxtKeyTyped

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new ADMIN_MAIN().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        if(checkSideCase()==true){
            JOptionPane.showMessageDialog(this, "empty fields","ERROR",2);
            return;
        }
        if(saveBtn.getText().equals("SAVE")){
            submit();
            Newbtn();
            return;
        }
        if(saveBtn.getText().equals("UPDATE")){
            update();
            Newbtn();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void savebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtn1ActionPerformed
        // TODO add your handling code here:
        Newbtn();
    }//GEN-LAST:event_savebtn1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
         if(checkSideCase()==true){
            JOptionPane.showMessageDialog(this, "empty fields","ERROR",2);
            return;
        }
        if(saveBtn.getText().equals("SAVE")){
            JOptionPane.showMessageDialog(this, "Unable to delete","ERROR",2);
            return;
        }
        int check = JOptionPane.showConfirmDialog(this, "Are you sure", "Deleting item", JOptionPane.YES_NO_OPTION);
        if(check==0){
            delete();
            Newbtn();
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_button3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Category.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Category().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea DEStxt;
    private javax.swing.JTextField IDtxt;
    private javax.swing.JTextField ITEMtxt;
    private panal.bgpanal bgpanal1;
    private ALL_UI_1.Button button1;
    private ALL_UI_1.Button button2;
    private ALL_UI_1.Button button3;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private panal.pane2 pane21;
    private panal.pane3 pane31;
    private ALL_UI_1.Button saveBtn;
    private ALL_UI_1.Button savebtn1;
    // End of variables declaration//GEN-END:variables
}
