/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketsystem;
import codeFiles.ConnectDB;
import codeFiles.usermodel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Gouhar Ali
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    
    Connection con ;
    PreparedStatement insert;
    ResultSet rs;
    public LOGIN() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        con = new ConnectDB().AccessDBConnection();
    }

    
    
    public boolean checkUser(){
        if (name.getText().equals("")&& pass.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Please Select a user");
            return false;
        }
        return true;
    } 
    
    public boolean STUDENTLOG(){
                try{
                    String username=name.getText();
                    String Password=pass.getText();
                    String type = user.getSelectedItem().toString();
                    insert=con.prepareStatement("SELECT* FROM `logs` WHERE USERNAME=? AND PASSWORD=? AND TYPE=?");
                    insert.setString(1,username);
                    insert.setString(2,Password);
                    insert.setString(3,type);
                        
                    rs=insert.executeQuery();
                        
                    if (rs.next()){
                        String g_Pass=rs.getString("password");
                        if (g_Pass.equals(Password)){
                            usermodel user = new usermodel();
                            user.setuser(rs.getString("ID"));
                            return true;
                        }    
                    }
                        
                }catch(Exception e){
                    JOptionPane.showMessageDialog(this, e);
                }
                return false;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanal1 = new panal.bgpanal();
        pane21 = new panal.pane2();
        button1 = new ALL_UI_1.Button();
        jLabel4 = new javax.swing.JLabel();
        pane31 = new panal.pane3();
        pass = new ALL_UI_1.TextField();
        name = new ALL_UI_1.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginbtn = new ALL_UI_1.Button();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user = new ALL.Combobox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgpanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setText("X");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button1.setRippleColor(new java.awt.Color(0, 0, 0));
        button1.setShadowColor(new java.awt.Color(0, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        pane21.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        pane21.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        bgpanal1.add(pane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 28));

        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setShadowColor(new java.awt.Color(0, 0, 0));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pane31.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 210, -1));

        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setShadowColor(new java.awt.Color(0, 0, 0));
        pane31.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 210, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Password");
        pane31.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("User");
        pane31.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSETS_files/icons8-cart-100.png"))); // NOI18N
        jLabel5.setText("Super Market");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pane31.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 260, 160));

        loginbtn.setText("LOGIN");
        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginbtn.setRippleColor(new java.awt.Color(0, 0, 0));
        loginbtn.setShadowColor(new java.awt.Color(0, 0, 0));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        pane31.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("System");
        pane31.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 260, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Super market managment Software");
        pane31.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 260, 40));

        user.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NONE", "ADMIN", "SELLER" }));
        user.setLabeText("");
        pane31.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 82, 190, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Username");
        pane31.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LOGIN");
        pane31.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 50));

        bgpanal1.add(pane31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 720, 360));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Software by m.uzair     cell : 03476442712");
        bgpanal1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 250, 30));

        getContentPane().add(bgpanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_button1ActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        if(checkUser()==false){
            return;
        }
        
        if(STUDENTLOG()==false){
            JOptionPane.showMessageDialog(this,"LOGIN unsuccessfull","WRONG INFO",2);
            return;
        }
        
        
        JOptionPane.showMessageDialog(this,"LOGIN successfull","Success",1);
        dispose();
        new ADMIN_MAIN().setVisible(true);
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panal.bgpanal bgpanal1;
    private ALL_UI_1.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private ALL_UI_1.Button loginbtn;
    private ALL_UI_1.TextField name;
    private panal.pane2 pane21;
    private panal.pane3 pane31;
    private ALL_UI_1.TextField pass;
    private ALL.Combobox user;
    // End of variables declaration//GEN-END:variables
}
